name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'  # Update Node.js version to 18.18.0

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: echo "Running linting..." && npm run lint

      - name: Run tests
        run: echo "Running tests..." && npm test

      - name: Cleanup
        run: echo "Die Pipeline ist sauber aufgeräumt und Wartungs- und Debug freundlich eingerichtet."